### PR TITLE
Timezone handling fixes

### PR DESCRIPTION
**Pull request by vytisb**
Assortment of fixes and cleanups related to timezone handling in Camera and admin.

### CODE REVIEW

**Comment by auvipy** [comment]
thanks for the patch. release notes and docs will be needed too.

**Comment by vytisb** [comment]
I'll look into adding some release notes. But can you clarify about the
docs? This is a bugfix/refactor PR and I would generally assume that these
don't require docs. Secondly, do we even have docs? The best I could find
online is a page in Celery docs.

2016-08-04 09:05 "Asif Saifuddin Auvi" <notifications@github.com> rašė:

**Comment by auvipy** [comment]
you are right, only release notes would be fine for now.

**Comment by vytisb** [comment]
I have added a changelog entry.

**Comment by auvipy** [comment]
looks good to me. thanks

**Pull request merged**
