### PR TITLE
Support for Django 1.7 migrations 

### PR DESCRIPTION
**Pull request by ionelmc**

### CODE REVIEW

**Comment by ionelmc** [comment]
Will fix #339

**Comment by AdrianLC** [comment]
Thank you for fixing this @ionelmc  :+1: 
Now if someone could, please, release this as soon as possible so I don't have to install from a git branch...
Thanks!

**Comment by ryanbagwell** [comment]
+1 on releasing this. Very much appreciated.

**Comment by ionelmc** [comment]
Odd, I've pushed them to master but this wasn't closed automatically

**Pull request closed without merging**
