### PR TITLE
prevent redundant migrations for py3 and #399

### PR DESCRIPTION
**Pull request by leonsim**

### CODE REVIEW

**Comment by auvipy** [comment]
@nickfishman are you talking about merging it?

**Comment by nickfishman** [comment]
@auvipy yes, merging this into master would be great.

**Comment by nickfishman** [comment]
@auvipy I see you already merged this in https://github.com/celery/django-celery/pull/405, thanks!

**Comment by auvipy** [comment]
closing in favor of #405

**Pull request closed without merging**
