### PR TITLE
Prevent hangs in django 1.8.

### PR DESCRIPTION
**Pull request by craigds**
Admin class unnecessarily populates the app-cache at import time, which causes django to lock
(because django.setup() is already halfway through, and it tries to avoid being called concurrently
by multiple threads, to avoid race conditions.)

This commit removes the unnecessary app cache populate, thus preventing the hangs.

### CODE REVIEW

**Comment by auvipy** [comment]
looks good. could you add some release note for this?

**Comment by auvipy** [comment]
Hi, could you rebase against master to fic the merge conflict?

**Comment by vytisb** [comment]
I think this issue should be already solved by #437, specifically [this commit](https://github.com/celery/django-celery/pull/437/commits/094af4d3431d8a9c9c6de96ab377deb7d8dec1e0) before the squash.

**Comment by auvipy** [comment]
closing for now then.

**Pull request closed without merging**
