### PR TITLE
Hot fix

### PR DESCRIPTION
**Pull request by AlkindiX**
Fix problem that occur in Django 1.10.* which is based on #472 . Thanks to @idesignedme for his contribution 
I have tested in Django 1.10 and the problem is gone

### CODE REVIEW

**Comment by auvipy** [comment]
thanks for the contribution. you might need to change test to fix the travis build error

**Comment by AlkindiX** [comment]
I will try to change it as soon as possible

On Oct 6, 2016, at 1:53 PM, Asif Saifuddin Auvi <notifications@github.com<mailto:notifications@github.com>> wrote:


thanks for the contribution. you might need to change test to fix the travis build error

-

**Comment by vytisb** [comment]
As I noted on the issue, the problem is already solved in 803234d03c8f03a149476365496263a921714bba, and this PR is unnecessary.

**Comment by idesignedme** [comment]
How do i add modifed files to my heroku app?

**Comment by auvipy** [comment]
check heroku and git docs

**Pull request closed without merging**
