### PR TITLE
prevent redundant migrations for py3 and #399

### LINKED ISSUE #399: problems with initial migration (py3 only)
To reproduce, simply:

```
pyvenv-3.5 venv
source venv/bin/activate
pip install django==1.8.6
pip install git+git://github.com/celery/django-celery.git@master
django-admin.py startproject demo
cd demo
<edit INSTALLED_APPS to include djcelery>
python manage.py makemigrations
```

Migrations are created when they should not be.  Additional makemigrations continually create migrations for djcelery.

This does not happen on python 2.7.

It happens on the current master branch and 3.1.17 on PyPi.

### PR DESCRIPTION
**Pull request by Pentusha**
Fixes #399 

Hello, django-celery constantly trying to create new migration each time.
```python
operations = [
    migrations.AlterField(
        model_name='taskmeta',
        name='status',
        field=models.CharField(
            default='PENDING', 
            choices=[
                ('SUCCESS', 'SUCCESS'), 
                ('RETRY', 'RETRY'), 
                ('STARTED', 'STARTED'), 
                ('REVOKED', 'REVOKED'), 
                ('RECEIVED', 'RECEIVED'), 
                ('PENDING', 'PENDING'), 
                ('FAILURE', 'FAILURE')
            ], 
            max_length=50, 
            verbose_name='state'
        ),
    ),
]
```

```python
operations = [
    migrations.AlterField(
        model_name='taskmeta',
        name='status',
        field=models.CharField(
            choices=[
                ('RETRY', 'RETRY'), 
                ('RECEIVED', 'RECEIVED'), 
                ('PENDING', 'PENDING'), 
                ('FAILURE', 'FAILURE'), 
                ('SUCCESS', 'SUCCESS'), 
                ('REVOKED', 'REVOKED'), 
                ('STARTED', 'STARTED')
            ], 
            verbose_name='state', 
            max_length=50, 
            default='PENDING'
        ),
    ),
]
```

```python
operations = [
    migrations.AlterField(
        model_name='taskmeta',
        name='status',
        field=models.CharField(
            max_length=50, 
            choices=[
                ('SUCCESS', 'SUCCESS'), 
                ('FAILURE', 'FAILURE'), 
                ('RETRY', 'RETRY'), 
                ('REVOKED', 'REVOKED'), 
                ('STARTED', 'STARTED'), 
                ('RECEIVED', 'RECEIVED'), 
                ('PENDING', 'PENDING')
            ], 
            default='PENDING', 
            verbose_name='state'
        ),
    ),
]
```
And so on...

### CODE REVIEW

**Comment by galuszkak** [comment]
+1 for merging this. I actually have the same problem and new migrations are generating all the time.

**Comment by firemark** [comment]
+1 It's weird but problem is only on postgresql, not sqlite or mysql o_O

**Comment by luiscastillocr** [comment]
Any update on this? just had a very uncomfortable afternoon trying to make the migrations work

@firemark, I  can confirm the issue is also present using mysqk

**Comment by Pentusha** [comment]
@luiscastillocr I had lost hope and just added git+https://github.com/Pentusha/django-celery.git@3.1 to my requirements file. You may have to re-create initial migrations, because it dependencies could be wrong.

I think words "THIS PROJECT IS NO LONGER REQUIRED" really mean "THIS PROJECT IS NO LONGER MAINTAINED",

**Comment by leonsim** [comment]
Please merge this. I got the same issue.

**Pull request merged**
