### PR TITLE
PeriodicTaskAdmin enhancements

### PR DESCRIPTION
**Pull request by kanemra**
Add enable/disable actions in PeriodicTaskAdmin. Extend list_display
and search_fields. Write unit tests.

This also contains #427 and #357

### CODE REVIEW

**Comment by kanemra** [comment]
Any comments or suggestions?

**Comment by auvipy** [comment]
looks good. A change log would be fine

**Comment by kanemra** [comment]
Done.

**Comment by auvipy** [comment]
thanks

**Pull request merged**
